version: '2'
services:
    vapor-dev:
        build:
            context: ./vapor/
            dockerfile: ./Dockerfile-dev
            args:
                - INSTALL_MYSQL=true
        image: vapor-dev
        container_name: vapor-dev

    cftr-api-dev:
        image: vapor-dev
        container_name: cftr-api-dev
        volumes:
            - ./../:/vapor
        ports:
            - "8080"
        depends_on:
            - vapor-dev
        tty: true

    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - ./nginx/vapor.conf:/etc/nginx/conf.d/default.conf
        links:
            - cftr-api-dev:app

    mysql:
        image: mysql:8.0.2
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=CFTR
            - MYSQL_ROOT_PASSWORD=root@pass
            - MYSQL_USER=vapor
            - MYSQL_PASSWORD=vapor@pass
        volumes:
            - mysql:/var/lib/mysql
        expose:
            - "3306"

volumes:
    mysql:
        driver: local
